spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TSURBot
    username: postgres
    password: Cracaziabra

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: false